### PR TITLE
#1027: Ensure namespace prefix name differences are not influencing XML equality

### LINKED ISSUE #1027: XmlStringMatcher is sensitive to different Namespace Prefixes since PlaceholderDifferenceEvaluator was added
**Describe the issue**
Unexpected error message when comparing XML that only differ in namespace prefix names:
```
Expected namespace prefix 'ns1' but was 'ns2'
```
Test case:
```
    @Test
    public void shouldMatchMatchingXMLWithDifferentNamespacePrefixes() {
        String matcher = "<a:element xmlns:a=\"the_namespace\"><a:key>some_key</a:key><a:value>some_value</a:value></a:element>";
        String matched = "<b:element xmlns:b=\"the_namespace\"><b:key>some_key</b:key><b:value>some_value</b:value></b:element>";
        assertTrue(new XmlStringMatcher(new MockServerLogger(), matcher).matches(matched));
    }
```

**What you are trying to do**
I'm trying to match webservice requests with a given test XML document. But the SOAP webservice framework keeps changing the namespace prefix names (for example from `ns1` to `ns2`) which results in a flaky test (with the given bug).

Also, I couldn't get the https://github.com/Siggen/jaxb2-namespace-prefix plugin to work with the https://www.mojohaus.org/jaxws-maven-plugin/ maven plugin which we are using in our project in order to get stable namespace prefixes.

**MockServer version**
5.11.2

**To Reproduce**
Add the following test case to `XmlStringMatcherTest`:
```
    @Test
    public void shouldMatchMatchingXMLWithDifferentNamespacePrefixes() {
        String matcher = "<a:element xmlns:a=\"the_namespace\"><a:key>some_key</a:key><a:value>some_value</a:value></a:element>";
        String matched = "<b:element xmlns:b=\"the_namespace\"><b:key>some_key</b:key><b:value>some_value</b:value></b:element>";
        assertTrue(new XmlStringMatcher(new MockServerLogger(), matcher).matches(matched));
    }
```

**Expected behaviour**
Namespace prefix names have no influence on XML equality.

### PR DESCRIPTION
**Pull request by KaiStapel**
Fixes #1027

### CODE REVIEW

**Comment by KaiStapel** [comment]
The test failures do not seem to be related to my change. Who may be able to help with that?

**Comment by jamesdbloom** [comment]
I have now fixed the PR pipeline (or at least worked around a bug in buildkite) can you please rebase the branch so the build can pass then I can merge your PR.

**Comment by KaiStapel** [comment]
@jamesdbloom I did. How do I re-trigger the pipeline?

**Comment by jamesdbloom** [comment]
Looks like the issue is related to the git repo as follows:

```bash
From https://github.com/jamesdbloom/mockserver

 * branch              refs/pull/1028/head -> FETCH_HEAD

[90m# FETCH_HEAD is now `ac296e935ef41025c0345c5699dc3ee02ff2b9e9`[0m
[90m$[0m git checkout -f 0af00d2288c75e59f81e0548991247126c7cdb52
fatal: reference is not a tree: 0af00d2288c75e59f81e0548991247126c7cdb52

[33mâš ï¸ Warning: Checkout failed! exit status 128 (Attempt 1/3 Retrying in 2s)[0m
^^^ +++
[90m$[0m git remote set-url origin https://github.com/jamesdbloom/mockserver.git
[90m$[0m git clean -ffxdq
[90m# Fetch and checkout pull request head from GitHub[0m
[90m$[0m git fetch -v --prune origin refs/pull/1028/head
POST git-upload-pack (395 bytes)

From https://github.com/jamesdbloom/mockserver

 * branch              refs/pull/1028/head -> FETCH_HEAD

[90m# FETCH_HEAD is now `ac296e935ef41025c0345c5699dc3ee02ff2b9e9`[0m
[90m$[0m git checkout -f 0af00d2288c75e59f81e0548991247126c7cdb52
fatal: reference is not a tree: 0af00d2288c75e59f81e0548991247126c7cdb52

[33mâš ï¸ Warning: Checkout failed! exit status 128 (Attempt 2/3 Retrying in 2s)[0m
^^^ +++
[90m$[0m git remote set-url origin https://github.com/jamesdbloom/mockserver.git
[90m$[0m git clean -ffxdq
[90m# Fetch and checkout pull request head from GitHub[0m
[90m$[0m git fetch -v --prune origin refs/pull/1028/head
POST git-upload-pack (395 bytes)

From https://github.com/jamesdbloom/mockserver

 * branch              refs/pull/1028/head -> FETCH_HEAD

[90m# FETCH_HEAD is now `ac296e935ef41025c0345c5699dc3ee02ff2b9e9`[0m
[90m$[0m git checkout -f 0af00d2288c75e59f81e0548991247126c7cdb52
fatal: reference is not a tree: 0af00d2288c75e59f81e0548991247126c7cdb52

[33mâš ï¸ Warning: Checkout failed! exit status 128 (Attempt 3/3 Retrying in 2s)[0m
^^^ +++
[31mðŸš¨ Error: exit status 128[0m
^^^ +++
~~~ Running global pre-exit hook
[90m$[0m /etc/buildkite-agent/hooks/pre-exit
```

**Comment by jamesdbloom** [comment]
I re-triggered the build but if you change the PR i.e. by another commit, etc the build should automatically re-trigger on its own.

**Comment by KaiStapel** [comment]
@jamesdbloom I still get test failures that seem unrelated to my change.

**Pull request merged**
